# Arduinoのボードの種類
BOARD_TAG           = nano328

# シリアルポートの設定
MONITOR_PORT        = /dev/ttyN328P

# ボーレートの設定
MONITOR_BAUDRATE    = 9600

# 独自のライブラリの追加
ARDUINO_LIBS    += 

# Arduino.mkのインクルード
include /usr/share/arduino/Arduino.mk
